# Generated by Django 4.2.16 on 2024-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=15, verbose_name='Número de Identificação Fiscal')),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('localidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
